module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.module.ts',
    '!**/index.ts',
    '!**/main.ts',
    '!**/*.dto.ts',
    '!**/*.entity.ts',
    '!**/*.interface.ts',
    '!**/*.enum.ts',
    '!**/*.constant.ts',
    '!**/*.decorator.ts',
    '!**/*.guard.ts',
    '!**/*.interceptor.ts',
    '!**/*.filter.ts',
    '!**/*.pipe.ts',
    '!**/*.strategy.ts',
    '!**/*.middleware.ts',
    '!**/*.gateway.ts',
    '!**/*.resolver.ts',
    '!**/*.graphql.ts',
    '!**/*.schema.ts',
    '!**/*.type.ts',
    '!**/*.config.ts',
    '!**/*.config.js',
    '!**/test/**',
    '!**/tests/**',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!**/coverage/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/node_modules/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
}; 